### ISSUE TITLE
Parallel-ize Tesseract? 

### ISSUE THREAD

**Issue by hadro** [atomotic/archiviiify#2]
Thanks for creating this and documenting it publicly! I'm in the middle of getting it up and running to work with the Brooklyn City Directory data in IA, which is a long-running hobby of mine. Archiviiify may make my life vastly easier, so thanks again.

I'm wondering if you'd consider implementing parallels for the OCR section, which could be done like this (I think):

`cat ocr/ITEM.list |  parallel --eta "tesseract -l eng {} {.} hocr"`

Or even in your OCR script the following, with one less step:
`find data/$ITEM/*.jp2 | parallel --eta "tesseract -l eng {} {.} hocr"`

(my version here is using the eng language flag, but could be whatever...)

For other projects, I've found that HOCR creation works quite well in parallel, since tesseract can just crunch through the pool of whatever discrete items you give it, and can make use of as many threads as you can throw at it.

I'd be happy to do a pull request with this tweak if you like, but thought I would ask since you may have already considered this

**Comment by hadro** [comment]
Ah, my mistake sorry -- as I get further into the process I realize that the OCR step is creating a single multipage hocr file, which would be trickier to deal with in terms of parallelization -- feel free to close up and sorry to bug you!

**Comment by atomotic** [comment]
hi! i'm glad that the documentation is useful.
as concerning the ocr, parallel+tesseract is something that i wanted to use at the very beginning.

to create a single multipage hocr i need to do more experiments with [hocr-combine](https://github.com/tmbdev/hocr-tools#hocr-combine), that was producing messy results in some tries.

the other option is to [index multiple ocr documents in solr](https://dbmdz.github.io/solr-ocrhighlighting/indexing/#multiple-files-per-solr-document-n1) and probably this is the way i want to try, that will also make simpler the ocr-fix script

 everything is rather than complete, i will improve more things in my spare time
* manifests are missing metadata
* the search api is not dealing well with errors
* configure a BASE_URL so that the whole stack could be published online on a public https url

**Comment by hadro** [comment]
Thanks for the response -- for my test case, I actually ended up doing the same thing you suggested, which was using parallel tesseract to create individual hocr files and then I used hocr-combine to bring them together.
At a glance, it seemed to work with the ocr-fix and index steps, but I admit I didn't do a deep analysis to look for potential problems.

In any event, it was great to see it work even as a prototype for what I've been trying to do!
I'll keep an eye on this for updates (though with no expectations, I know everyone has a lot of projects on their plates), and thanks again

**Comment by atomotic** [comment]
closing this old ticket. in the meanwhile Archive.org has made a [transition from abby to tesseract](https://archive.org/developers/ocr.html).
I just rewrote everything https://github.com/atomotic/archiviiify and full-text search has not yet landed here, I will think of a more minimalistic solution rather than the full Solr stack.
